### ISSUE TITLE
Add a generic property for the username in the Connection profile

### ISSUE THREAD

**Issue by aurelticot** [verida/data-connector-server#106]
The Connection object has a `profile` property containing the user's account information. While the `name` and `avatar` are likely to be generic enough accross all kind of providers, the user's account reference/username is different.

It is often an email (gmail, linkedin, ..), but can also be a handle (twitter, ..) or a phone number (telegram, ...)

The current profile seems to provide that reference but the name of the property is specific, for instance Gmail wil provide an `email` property.

We need a generic property to display which account is connected whatever its type (email, handle, phone number, ...), so we don't have to wonder wethere it's the `email` property or another one.

It is obviously the user-facing reference/username, not the technical one that might be used in the `id`.

I suggest the term `username`.

```ts
{
  "profile": {
    "id":"1159451234567890123456",
    "username":"john@example.com",
    "name":"john Doe",
    "avatar":{},
    "email":"john@example.com"
  }
}
```

**Comment by tahpot** [comment]
At the moment, this data is (for the most part) coming directly from the `passport-js` library implementation for each connection.

This is good in theory, but not always possible.

For example; Facebook only guarantees a user ID. There is no guarantee of a username or any other human friendly identifier....

**Comment by aurelticot** [comment]
As discussed on Discord, we will have an optional `username` property to better reflect the reality of some providers.
It is our own logic to set the `username` from whatever is appropriate from the provider on a case-by-case basis (handle for twitter, email for google, etc.)

Additionally, we will add a `readableId` which would either be the same value as `username` if defined or as a fallback, is set with the value of `profile.id`.

This `readableId`, being always defined, can be used in the apps' UI. For the few cases where it's a technical id, it would not be a big deal.
