### ISSUE TITLE
Consider returning early when responding to `/sync`

### ISSUE THREAD

**Issue by aurelticot** [verida/data-connector-server#111]
Calling the `/sync` endpoint triggers the connection syncing. This operation can take several minutes.

The request currently hangs until the operation is finished to respond to the caller.

Consider triggering the sync operation without waiting for it to finish and return a 200 or 204.

To get informed of the end of the sync, the idea is to listen to the connections `status` via an event source (or directly the Verida record in the short-term).

**Comment by tahpot** [comment]
Added a `instantComplete` option to `/sync` and `/sync/:connectionId`.
