### ISSUE TITLE
Restructure the API endpoints

### ISSUE THREAD

**Issue by aurelticot** [verida/data-connector-server#112]
>[!NOTE]
> This ticket aims at suggesting a structure of the API in the long term, particularly when the Data Connector Server will be its own server, separated from the Private Data API (fetching any data, LLM, search, etc.).
> 
> In the short-term, we can take shortcuts and leverage the data API endpoints instead of having dedicated endpoints (for the logs for instance)

# Suggested long-term API structure

Considering:

BASE_URL: "http://domain.com"
API_URL: `${BASE_URL}/api/rest/v1`

(Using `/rest` to be future-proof, in case a `/api/graphql` endpoint is necessary)

## Data Connections API endpoints

All these endpoints are available under `API_URL`

### Providers

<details>
<summary>GET /providers</summary>
<p>Get all the provider definitions, include the handler definitions</p>
</details>

### Provider

<details>
<summary>GET /providers/:providerId</summary>
<p>Get a given provider definition</p>
</details>

### Connections

<details>
<summary>GET /connections</summary>
<p>To get all the connections. Could be a POST as the query (filter, sorting, pagination) is better in the body than in query/search params.</p>
</details>

<details>
<summary>GET /connections/watch</summary>
<p>Event Source endpoint. Get updates on all the connections, particularly theirs status. Could be a POST as the query (filter, sorting, pagination) is better in the body than in query/search params.</p>
</details>

<details>
<summary>POST /connections/sync</summary>
<p>Sync all the connections at once</p>
</details>

<details>
<summary>GET /connections/logs</summary>
<p>Get all the existing logs. Could be a POST to pass a query in the body.</p>
</details> 

<details>
<summary>GET /connections/logs/watch</summary>
<p>Event Source endpoint. Listen to new logs for all connections. Could be a POST to pass a query in the body.</p>
</details>

### Connection

<details>
<summary>GET /connections/:connectionId</summary>
<p>Get a connection object by its id</p>
</details>

<details>
<summary>PUT /connections/:connectionId</summary>
<p>To update the configuration of the connection. Not all properties of the connection object can be updated though, so the controller will have to carefully extract the allowed field from the body.</p>
</details>

<details>
<summary>DELETE /connections/:connectionId</summary>
<p>Disconnect a connection</p>
</details>

<details>
<summary>POST /connections/:connectionId/watch</summary>
<p>Event Source endpoint. To listen to updates on the connection</p>
</details>

<details>
<summary>POST /connections/:connectionId/pause</summary>
<p>To pause a connection</p>
</details>

<details>
<summary>POST /connections/:connectionId/resume</summary>
<p>To resume a paused connection</p>
</details>

<details>
<summary>POST /connections/:connectionId/sync</summary>
<p>To trigger the sync operation of the connection. Doesn't wait for the sync to finish to respond, doesn't return anything apart from whether triggering the sync was successful. The actual result of the sync can be checked via the status of the connection (also the /watch endpoint to listen to changes on the status)</p>
</details>

<details>
<summary>GET /connections/:connectionId/logs</summary>
<p>Get the logs of a given connection. Could be a POST to pass a query in the body.</p>
</details>

<details>
<summary>GET /connections/:connectionId/logs/watch</summary>
<p>Event Source endpoint. Listen to new logs for a given connection. Could be a POST to pass a query in the body.</p>
</details>

## Data Connections other routes

These routes are available under `BASE_URL`, not `API_URL` (`/api/rest/v1`) because they are not API endpoints, but are actual pages opened by the browser.

<details>
<summary>/providers/:providerId/connect</summary>
<p>To connect to a provider using their authentication/authorisation mechanism (OAuth)</p>
</details> 

<details>
<summary>/providers/:providerId/callback</summary>
<p>Passed to the provider OAuth mechanism to get the information back and creates the Connection object</p>
</details> 

# Short-term needed updates

In the short-term, the `/connections`, the `/connections/logs`, the `/connections/:connectionId`, and the `/connections/:connectionId/logs` endpoints are not needed as the generic `/db/query` and `/db/get` endpoints can be used instead.

The `/.../watch` endpoints to listen to changes would be nice but not a priority as we can refetch the data occasionally.

The `/providers/:providerId` is also not needed as there is not a lot of providers, so `/providers` is enough for now.

The current `GET /sync` sure works, even though a `POST /connections/:connectionId/sync` would be more explicit and more RESTFUL.

Same for the `GET /provider/disconnect/:provider`, which works but would be more RESTFUL with as a `DELETE /connections/:connectionId`.

The **only actual current need** is the ability to update a connection as well as pause/resume it. When updating we have to be careful on what should be excluded from the update (providerId, handlerId, status, etc.) and what can be updated (basically just the config/options).

**Comment by tahpot** [comment]
Immediate tasks:

- [x] Refactor to use `/api/rest/v1`
- [x] Add `/db/watch` and `/ds/watch` EventSource endpoints
- [ ] Move `/providers/:providerId/connect` and `/providers/:providerId/callback` outside of `/api/rest/v1` and to `/`
- [ ] Add `GET /providers/:providerId`
- [ ] Move `GET /sync` to `POST /connections/sync`
- [ ] Add `POST /connections/:connectionId/sync`
- [ ] Add `PUT /connections/:connectionId` to update a connection (only some properties)
- [ ] Move `GET /provider/disconnect/:provider` to `DELETE /connections/:connectionId`
- [ ] Delete `/sync/logs`
- [ ] Move `/sync/status` to `GET /connections`
