### ISSUE TITLE
Add pagination details in the query endpoint responses

### ISSUE THREAD

**Issue by aurelticot** [verida/data-connector-server#113]
For `/db/query` and `/ds/query`, the response is simply composed of an `items` array.

It would be helpful to also return details of the pagination:

```jsonc
{
  "items": [],
  "limit": 10, // not particulary necessary as it comes from the request originally but could be useful in some cases
  "skipped": 30, // not particulary necessary as it comes from the request originally but could be useful in some cases
  "totalCount": 1234, // This is the useful information, so we can define the pagination
}
```

The `totalCount` should take into accout the filter of the query.

For `limit` and `skipped`, may there are other best practices for the terminology.

**Comment by tahpot** [comment]
> The `totalCount` should take into accout the filter of the query.

PouchDb doesn't support a total count with a filter applied. I can return a count of all records, without the filter. I *could* code something manually to iterate through all the pages to calculate a total, but that seems like a waste of resources.

The rest is fine.

**Comment by aurelticot** [comment]
>  I can return a count of all records, without the filter

Ok, but if you can name the variable `unfilteredTotalCount` that would avoid ambiguity.

I'll try to figure out a thing in the UI about the pagination.
