### ISSUE TITLE
Google Calendar issues

### ISSUE THREAD

**Issue by tahpot** [verida/data-connector-server#155]
Some issues have been identified:

1. Calendars of other users (not your own) are being added, but they shouldn't be.
2. Recurring events are being added well into the future (ie: 2035). Need to limit / cap that somehow.

Create unit tests for any fixes that confirm the changes are working properly.

**Comment by chime3** [comment]
Please confirm these two things @tahpot (cc @ryank000 )
- Calendar list involves subscribed calendars which are the other users created and default calendars such as Holidays, Birthdays. They are all tied to the Google account, not other users' calendars. Do you want to apply any filters or ignore?
- Please tell me the limit cap of recurring events

**Comment by tahpot** [comment]
- Only process calendars created by the user
- Limit recurring events to 1 month in the future
