### ISSUE TITLE
Refactor for efficiency

### ISSUE THREAD

**Issue by tahpot** [verida/data-connector-server#58]
The current architecture has the server create a new database for every sync request.

It then provides the Wallet access to that database, so the wallet can sync this new data. This is inefficient from a storage perspective, creates timing issues and makes it difficult to make the sync data in a way to only fetch the new items.

Now that we support `accessTokens`, we can provide time limited access for the server to read and write directly to user's vault storage collections. This does increase the security risk surface area a little, but the performance and user experience trade-offs are worth it.

![Data Connector New Architecture](https://github.com/verida/data-connector-server/assets/164973/024d01b2-cd59-4130-9c12-33bfcc13403f)

It will work like this:

1. User authenticates via the data connector server (no change)
2. Verida Vault saves the user's `accessToken` and `refreshToken` for the connection into it's own private database of connections (no change)
3. Verida Vault periodically calls a `sync()` method on the data connector server
4. Data connector server handles the `sync()` request, pulls the latest data from the connector API (ie: facebook) and saves the new data directly into the user's Verida Vault database

In order for this to work, the data api connector `sync()` method will need to accept the following parameters:

1. `veridaDatabaseEndpointUri` The endpoint of the Verida database to connect to
2. `veridaDatabaseAccessToken` The Verida database access token that has 20 minute expiry
3. `veridaDatabaseEncryptionKey` The Verida database encryption key that is used to encrypt / decrypt data from the Verida database
4. `accessToken` The access token for the connection API (ie: facebook)
5. `refreshToken` The refresh token for the connection API (ie: facebook)

Where `veridaDatabase` is an encrypted database on the Verida network, owned and controlled by the Verida Vault application.

**Comment by InfiniteAengus** [comment]
Currently we are using `openDatastore` method to create a new database and store data which has enforced schema.
But I think we should use `openDatabase ` for refactoring and store the data which requires accessToken and encryption key. right?
Additionally, we might need to store some additional variables so I think it's better to use the no-schema database.

**Comment by tahpot** [comment]
This scope of work is no longer correct as we are moving to a confidential compute model.

**Comment by tahpot** [comment]
Replaced by #63
