### ISSUE TITLE
[New handler] Google Drive Documents

### ISSUE THREAD

**Issue by tahpot** [verida/data-connector-server#85]
Add GSuite drive files into a new "documents" datastore.

Request the scope `https://www.googleapis.com/auth/drive.readonly`

Support the following document types:

- Docs (Google documents, Word documents, PDFs)
- Slides
- Spreadsheets

We don't want to store the actual document, but do want to store the text of the document and a link to the actual document.

Note: PDF files can be converted to text with this code: https://github.com/verida/data-connector-server/blob/0332d3c38b4c2c65e85a6e7fb9cb204d457b15f7/src/providers/google/helpers.ts#L133

**Comment by chime3** [comment]
> Add GSuite drive files into a new "documents" datastore.
> 
> Request the scope `https://www.googleapis.com/auth/drive.readonly`
> 
> Support the following document types:
> 
> * Docs (Google documents, Word documents, PDFs)
> * Slides
> * Spreadsheets
> 
> We don't want to store the actual document, but do want to store the text of the document and a link to the actual document.
> 
> Note: PDF files can be converted to text with this code:
> 
> https://github.com/verida/data-connector-server/blob/0332d3c38b4c2c65e85a6e7fb9cb204d457b15f7/src/providers/google/helpers.ts#L133

Will you create `Document` schema? @tahpot

**Comment by tahpot** [comment]
> Will you create `Document` schema? @tahpot

Yes, I'll share with you later today

**Comment by tahpot** [comment]
@chime3 See https://common.schemas.verida.io/document/v0.1.0/schema.json

**Comment by chime3** [comment]
> @chime3 See https://common.schemas.verida.io/document/v0.1.0/schema.json

Okay
