### ISSUE TITLE
MVP builder tasks

### ISSUE THREAD

**Issue by tahpot** [verida/data-connector-server#89]
Core Sync:

- [x] `CompletedRangeTracker` (rename to `ItemsRangeTracker`)
- [x] Google: Update to use `ItemsRangeTracker`
- [x] Google: Fix youtube (and gmail?) re-processing the same items (bug caused by handler not saving sync position correctly)
- [x] Gmail: Fix html escaping of text email
- [x] Populate `syncPosition.statusMessage` for all handlers
- [x] Handle schema changes to syncPosition status and profile avatar
- [x] Sync handlers in parallel
- [x] ~Telegram: Avoid saving chat group every processing~ Not possible because sync state is updated every processing run. Instead the protocol will support compaction in the future to manage disk space concerns.
- [x] ~Telegram: Avoid saving tdlib auth file every batch?~ No TDLIB manages the binfile size with garbage collection. Future protocol compaction will help manage the increase in file size.

Robustness:

- [x] Support garbage collection timeout of cached network connections per DID
- [x] ~Ensure garbage collection deletes local cached pouchdb databases~ Delete pouchdb files on server start.

UX:

- [x] Split interface into `Developers` and `Users`
- [x] Provide `Sync` and `Force Sync` as two different sync options

Developers:

- [x] Complete `API Playground`
- [x] Complete `About` documentation
- [x] Support populating Google avatar

**Comment by tahpot** [comment]
Outstanding tasks for @chime3 to complete once youtube and google are complete:


- [ ]  Populate syncPosition.statusMessage for youtube, google suite
- [ ] Google Docs: Update to use files schema instead of documents (see excited designs)

**Comment by chime3** [comment]
> * [ ]  Google Docs: Update to use files schema instead of documents (see excited designs)

Could you give me some more explanation regarding to file schema and design? schema URI, figma link etc @tahpot

**Comment by tahpot** [comment]
> > * [ ]   Google Docs: Update to use files schema instead of documents (see excited designs)
> 
> Could you give me some more explanation regarding to file schema and design? schema URI, figma link etc @tahpot

Yes, however it's not yet ready, so no need to work on this just yet.

**Comment by chime3** [comment]
> > > * [ ]    Google Docs: Update to use files schema instead of documents (see excited designs)
> > 
> > 
> > Could you give me some more explanation regarding to file schema and design? schema URI, figma link etc @tahpot
> 
> Yes, however it's not yet ready, so no need to work on this just yet.

Okay
